### ISSUE TITLE
"docker build" requires exactly 1 argument.

### ISSUE THREAD

**Issue by dal233** [PacktPublishing/Learn-Grafana-7.0#5]
I get this message:

`"docker build" requires exactly 1 argument.`

When I run this command in Chapter 6:

`docker build --pull --tag weather`

When I replace the above command with:

`docker build --pull --tag bin .`

It completes the build.

Just an FYI.

**Comment by esalituro** [comment]
Good catch! Thank you for the feedback

```sh
    $ docker build --pull --tag weather .
```

should work as well. Just remember to reference the correct image tag when you `docker run` the container.

**Comment by esalituro** [comment]
This should be updated in the `ERRATA.md`
