### ISSUE TITLE
Query options/the Min interval: 1m  

### ISSUE THREAD

**Issue by dal233** [PacktPublishing/Learn-Grafana-7.0#6]
Repeatedly in the book, there is an instruction to set the min interval to 1m.  However, when I click on Query options, the min interval is never something I can change (always 2m).

**Comment by esalituro** [comment]
I'm not exactly sure what might be going on there. If you could describe more specifically where in book you're referring and maybe a screencap, I can try to replicate your problem. It sounds like you are doing the right thing. 

After clicking on **`Query options`**, you should be able to type `1m` in the text box next to **`Min interval`** `<TAB>` should then update the entry in the **`Interval`** box below it.
